name: Daily Commit

on:
  schedule:
    - cron: "0 5 * * *"  # ساعت 08:30 صبح ایران
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Make a change
        run: |
          echo "$(date -u +"%Y-%m-%d %H:%M:%S UTC") - commit by GitHub Actions" >> log.txt

      - name: Commit & push if changed
        run: |
          git config user.name "ahmadrz1379"
          git config user.email "aahmadrezarezaee@gmail.com"
          git add log.txt
          if git diff --staged --quiet; then
            echo "nothing to commit"
          else
            git commit -m "daily commit - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi
